### pymongo
- python 에서 MongoDB 작업을 위한 도구
- pip install pymongo==2.8.1

In [1]:
# 패키지 불러오기
import pymongo
import pandas as pd

import zigbang as zb # zigbang.py가 본 주피터 노트북 파일과 동일한 경로에 있어야 함

In [2]:
# 데이터베이스 서버 연결 - 여러분의 AWS Public IP를 입력해주세요.
client = pymongo.MongoClient("mongodb://your_public_ip_address/:27017/")

In [ ]:
client

In [ ]:
# 데이터 베이스와 컬렉션 생성
zigbang = client.crawling.zigbang
zigbang

In [5]:
items = zb.oneroom('성수동')
len(items)

11

In [6]:
items

[{'section_type': None,
  'item_id': 22519960,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22519960/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 1000,
  'rent': 40,
  'size_m2': 16.53,
  '공급면적': {'m2': 16.53, 'p': '5'},
  '전용면적': {'m2': 16.53, 'p': '5'},
  'room_type_title': None,
  'floor': '3',
  'floor_string': '3',
  'building_floor': '4',
  'title': '초역세권 저렴한 원룸',
  'is_first_movein': None,
  'room_type': '01',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54331162361157, 'lng': 127.04473646828113},
  'is_zzim': False,
  'status': True,
  'service_type': '원룸',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '5.5',
  'reg_date': '2020-06-17T19:30:17+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22476923,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22476923/1.jpg',
  'sales_type': '전세',
  'sales_title': '전세',
  'deposit': 10000,
  'rent': 0,
  'size_m2': 39.67,
  '공급면적': {'m2': 39.67, 'p': '12'},
  '전용면적': {'m2': 36.36, 'p': '11'},
  'room_type_title': None,
  'floor': '2',
  'floor_string': '2',
  'building_floor': '3',
  'title': '서울숲 2룸 시세대비 저렴한 전세 대출불가',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54734143612069, 'lng': 127.04074281362405},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '0',
  'reg_date': '2020-06-15T16:45:10+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22246202,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22246202/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 2000,
  'rent': 50,
  'size_m2': 66.12,
  '공급면적': {'m2': 66.12, 'p': '20'},
  '전용면적': {'m2': 62.81, 'p': '19'},
  'room_type_title': None,
  'floor': '1',
  'floor_string': '1',
  'building_floor': '2',
  'title': '■▣  투룸  //  2000-50  ▣■',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54780566844634, 'lng': 127.04001627166997},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '0',
  'reg_date': '2020-06-18T14:38:16+09:00',
  'is_new': True},
 {'section_type': None,
  'item_id': 22455991,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22455991/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 7000,
  'rent': 50,
  'size_m2': 52.89,
  '공급면적': {'m2': 52.89, 'p': '16'},
  '전용면적': {'m2': 49.59, 'p': '15'},
  'room_type_title': None,
  'floor': '4',
  'floor_string': '4',
  'building_floor': '5',
  'title': '서울숲위치  올수리 투룸 월세 즉시입주 대출불가',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.548129471258974, 'lng': 127.04296326613824},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': ['추천'],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '0',
  'reg_date': '2020-06-15T10:56:00+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22456926,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22456926/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 7000,
  'rent': 50,
  'size_m2': 46.28,
  '공급면적': {'m2': 46.28, 'p': '14'},
  '전용면적': {'m2': 42.98, 'p': '13'},
  'room_type_title': None,
  'floor': '4',
  'floor_string': '4',
  'building_floor': '5',
  'title': '♣ 서울숲길, 올수리된 2룸 ,  전세대출X♣',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54762670781591, 'lng': 127.04292893068747},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '0',
  'reg_date': '2020-06-13T18:29:47+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22336641,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22336641/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 1000,
  'rent': 75,
  'size_m2': 29.09,
  '공급면적': {'m2': 29.09, 'p': '8.8'},
  '전용면적': {'m2': 29.09, 'p': '8.8'},
  'room_type_title': None,
  'floor': '3',
  'floor_string': '3',
  'building_floor': '6',
  'title': '뚝섬역 도보 3분. 전용 9평 넓은  원룸~',
  'is_first_movein': None,
  'room_type': '01',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54884064446169, 'lng': 127.04290338052412},
  'is_zzim': False,
  'status': True,
  'service_type': '원룸',
  'tags': ['추천'],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '5',
  'reg_date': '2020-06-06T15:27:30+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22124423,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22124423/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 1000,
  'rent': 45,
  'size_m2': 19.83,
  '공급면적': {'m2': 19.83, 'p': '6'},
  '전용면적': {'m2': 19.83, 'p': '6'},
  'room_type_title': None,
  'floor': '4',
  'floor_string': '4',
  'building_floor': '6',
  'title': '뚝섬역 2분 잘 관리된 풀옵션 원룸입니다^^',
  'is_first_movein': None,
  'room_type': '01',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.548618017789806, 'lng': 127.04495878880407},
  'is_zzim': False,
  'status': True,
  'service_type': '원룸',
  'tags': ['추천'],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '5',
  'reg_date': '2020-05-25T18:18:31+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22375291,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22375291/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 1000,
  'rent': 45,
  'size_m2': 16.52,
  '공급면적': {'m2': 16.52, 'p': '5'},
  '전용면적': {'m2': 16.52, 'p': '5'},
  'room_type_title': None,
  'floor': '4',
  'floor_string': '4',
  'building_floor': '5',
  'title': '뚝섬역 초역세권 편리한 원룸',
  'is_first_movein': None,
  'room_type': '01',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54861020493993, 'lng': 127.04492865123292},
  'is_zzim': False,
  'status': True,
  'service_type': '원룸',
  'tags': ['추천'],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '5',
  'reg_date': '2020-06-13T11:08:51+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22474522,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22474522/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 1000,
  'rent': 45,
  'size_m2': 16.52,
  '공급면적': {'m2': 16.52, 'p': '5'},
  '전용면적': {'m2': 16.52, 'p': '5'},
  'room_type_title': None,
  'floor': '4',
  'floor_string': '4',
  'building_floor': '5',
  'title': '♣뚝섬역 초역세권,  풀옵션, 깨끗함 ♣',
  'is_first_movein': None,
  'room_type': '01',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.54911567290124, 'lng': 127.04497369039159},
  'is_zzim': False,
  'status': True,
  'service_type': '원룸',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '5',
  'reg_date': '2020-06-15T15:08:15+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 21958007,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/21958007/1.jpg',
  'sales_type': '전세',
  'sales_title': '전세',
  'deposit': 12000,
  'rent': 0,
  'size_m2': 39.67,
  '공급면적': {'m2': 39.67, 'p': '12'},
  '전용면적': {'m2': 36.36, 'p': '11'},
  'room_type_title': None,
  'floor': '2',
  'floor_string': '2',
  'building_floor': '5',
  'title': '◆다가구주택 2층 투룸 귀한 전세 매물입니다.◆',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.55056370581985, 'lng': 127.04520743831465},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': ['추천'],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '2.1',
  'reg_date': '2020-06-04T18:40:21+09:00',
  'is_new': False},
 {'section_type': None,
  'item_id': 22518043,
  'images_thumbnail': 'https://ic.zigbang.com/ic/items/22518043/1.jpg',
  'sales_type': '월세',
  'sales_title': '월세',
  'deposit': 10000,
  'rent': 70,
  'size_m2': 66.12,
  '공급면적': {'m2': 66.12, 'p': '20'},
  '전용면적': {'m2': 37.36, 'p': '11.3'},
  'room_type_title': None,
  'floor': '6',
  'floor_string': '6',
  'building_floor': '6',
  'title': '신축 2년   깨끗한 신혼부부 빌라~',
  'is_first_movein': None,
  'room_type': '04',
  'address': '성동구 성수동1가',
  'random_location': {'lat': 37.55138754958722, 'lng': 127.04603480872848},
  'is_zzim': False,
  'status': True,
  'service_type': '빌라',
  'tags': [],
  'address1': '서울시 성동구 성수동1가',
  'address2': None,
  'address3': None,
  'manage_cost': '6',
  'reg_date': '2020-06-17T18:08:11+09:00',
  'is_new': False}]

In [7]:
# 데이터프레임 저장
sungsoo_df = pd.DataFrame(items)
# 필요한 컬럼만 추출
columns = ["address1", "size_m2", "floor", "sales_type", "rent", "deposit"]
sungsoo_df = sungsoo_df[columns]
sungsoo_df.tail(2)

         address1  size_m2 floor sales_type  rent  deposit
9   서울시 성동구 성수동1가    39.67     2         전세     0    12000
10  서울시 성동구 성수동1가    66.12     6         월세    70    10000

In [8]:
zigbang2 = client.crawling.zigbang2

In [9]:
# 딕셔너리 형태로 변환
items = sungsoo_df.to_dict("records")
items[0]

{'address1': '서울시 성동구 성수동1가',
 'size_m2': 16.53,
 'floor': '3',
 'sales_type': '월세',
 'rent': 40,
 'deposit': 1000}

In [10]:
ids = zigbang2.insert(items)

In [11]:
results = zigbang2.find()

In [12]:
QUERY = {"rent": {"$lte": 50}}
results = zigbang2.find(QUERY)
pd.DataFrame(results).tail()

,_id,address1,deposit,floor,rent,sales_type,size_m2
4,5eecd541cd37df3097d62d2d,서울시 성동구 성수동1가,7000,4,50,월세,46.28
5,5eecd541cd37df3097d62d2f,서울시 성동구 성수동1가,1000,4,45,월세,19.83
6,5eecd541cd37df3097d62d30,서울시 성동구 성수동1가,1000,4,45,월세,16.52
7,5eecd541cd37df3097d62d31,서울시 성동구 성수동1가,1000,4,45,월세,16.52
8,5eecd541cd37df3097d62d32,서울시 성동구 성수동1가,12000,2,0,전세,39.67

In [13]:
# 컬렉션 삭제
client.crawling.drop_collection("zigbang")

In [14]:
# 데이터 베이스 삭제
client.drop_database("crawling")